#!/bin/sh

# applies stimuli to learn assemblies A, B, C; subsequently consolidates; weights are initialized with random values

# uses 'screen' to run process(es) in the background

cd "organization_randweight/1st/FIRST"
screen -d -m /bin/sh run # run process(es) in the background using 'screen'
cd ../../..
