#!/bin/sh

# copies data from learning/consolidation simulations in 'organization_noLTD/' and simulates spontaneous activation

# uses 'screen' to run process(es) in the background

learned_dir="../organization_noLTD/3rd"

cd "activation_noLTD/"

### 10 ###
cd OVERLAP10
cp "../net_activation.out" .
cp "../../../../analysis/overlapParadigms.py" .
cp "../../../../analysis/utilityFunctions.py" .
cp "../../../../analysis/assemblyAvalancheStatistics.py" .
cp "../$learned_dir/OVERLAP10/connections.txt" .
cp "../$learned_dir/OVERLAP10/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run 
cd "../OVERLAP10 no AC, no ABC"
cp "../net_activation.out" .
cp "../../../../analysis/overlapParadigms.py" .
cp "../../../../analysis/utilityFunctions.py" .
cp "../../../../analysis/assemblyAvalancheStatistics.py" .
cp "../$learned_dir/OVERLAP10 no AC, no ABC/connections.txt" .
cp "../$learned_dir/OVERLAP10 no AC, no ABC/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run
cd "../OVERLAP10 no BC, no ABC"
cp "../net_activation.out" .
cp "../../../../analysis/overlapParadigms.py" .
cp "../../../../analysis/utilityFunctions.py" .
cp "../../../../analysis/assemblyAvalancheStatistics.py" .
cp "../$learned_dir/OVERLAP10 no BC, no ABC/connections.txt" .
cp "../$learned_dir/OVERLAP10 no BC, no ABC/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run

### NO ###
cd ../NOOVERLAP
cp "../net_activation.out" .
cp "../../../../analysis/overlapParadigms.py" .
cp "../../../../analysis/utilityFunctions.py" .
cp "../../../../analysis/assemblyAvalancheStatistics.py" .
cp "../$learned_dir/NOOVERLAP/connections.txt" .
cp "../$learned_dir/NOOVERLAP/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run

cd ../..
