#!/bin/sh

# first copies data from learning/consolidation simulations in 'organization/' and then simulates recall through stimulation of a fraction of the neurons of each assembly

cd recall/

### NOOVERLAP ###
cd NOOVERLAP
cp "../netA.out" .
cp "../netB.out" .
cp "../netC.out" .
cp "../../../../analysis/overlapParadigms.py" .
cp "../../../../analysis/utilityFunctions.py" .
cp "../../../../analysis/assemblyAvalancheStatistics.py" .
cp "../$organization_dir/3rd/NOOVERLAP/connections.txt" .
cp "../$organization_dir/3rd/NOOVERLAP/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run

### Control ###
cd ../Control
cp "../netA.out" .
cp "../netB.out" .
cp "../netC.out" .
cp "../../../../analysis/overlapParadigms.py" .
cp "../../../../analysis/utilityFunctions.py" .
cp "../../../../analysis/assemblyAvalancheStatistics.py" .
cp "../$organization_dir/1st/FIRST/connections.txt" .
cp "../$organization_dir/1st/FIRST/"*/*/*"_net_0.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run

cd ../..
