#!/bin/sh

mkdir 2N1S
cd 2N1S
cp ../2N1S.out .

num_trials=100

for (( i=1; i <= $num_trials; ++i ))
do
    ./2N1S.out -learn=STET -Ca_pre=1.0 -Ca_post=0.2758 -purpose= 
done

for (( i=1; i <= $num_trials; ++i ))
do
    ./2N1S.out -learn=WTET -Ca_pre=1.0 -Ca_post=0.2758 -purpose= 
done

for (( i=1; i <= $num_trials; ++i ))
do
    ./2N1S.out -learn=SLFS -Ca_pre=1.0 -Ca_post=0.2758 -purpose= 
done

for (( i=1; i <= $num_trials; ++i ))
do
    ./2N1S.out -learn=WLFS -Ca_pre=1.0 -Ca_post=0.2758 -purpose= 
done

cd ..
