#!/bin/sh

cd "OVERLAP10 no AC, no ABC/C"
cp "../../../../activation/net_activation.out" .
cp "../run" .
cp "../../../1. Priming/OVERLAP10 no AC, no ABC/C/connections.txt" connections.txt
cp "../../../1. Priming/OVERLAP10 no AC, no ABC/C/"*/network_plots/*_net_25220.0.txt coupling_strengths.txt
cp "../../../../../../analysis/overlapParadigms.py" .
cp "../../../../../../analysis/utilityFunctions.py" .
cp "../../../../../../analysis/assemblyAvalancheStatistics.py" .
screen -d -m /bin/sh run

cd ../..
