#!/bin/sh

current_working_dir=${PWD}
cd ..

rm -f code.zip
zip -q -D code.zip * -x *.out *.o *.txt
g++ -std=c++11 -O2 NetworkMain.cpp -Wl,--format=binary -Wl,code.zip -Wl,plotFunctions.py -Wl,--format=default -D ACTIVATION_P2 \
    -Wno-unused-result -lboost_serialization -static -o "net_activation.out"
rm -f code.zip

cd "${current_working_dir}"
