#!/bin/sh

current_working_dir=${PWD}
cd ..

head_out_dir="../simulation-bin/run_binary_paper2"
out_dir="${head_out_dir}/recall"
mkdir -p ${out_dir}

# see 'Definitions.hpp' for values of CORE_SHAPE_CMD

rm -f code.zip
zip -q -D code.zip * -x *.out *.o *.txt

g++ -std=c++11 -O1 NetworkMain.cpp -Wl,--format=binary -Wl,code.zip -Wl,plotFunctions.py -Wl,--format=default -D RECALL_P2 \
    -D CORE_SHAPE_CMD=1 -Wno-unused-result -lboost_serialization -static -o "${out_dir}/netA.out"

g++ -std=c++11 -O1 NetworkMain.cpp -Wl,--format=binary -Wl,code.zip -Wl,plotFunctions.py -Wl,--format=default -D RECALL_P2 \
    -D CORE_SHAPE_CMD=2 -Wno-unused-result -lboost_serialization -static -o "${out_dir}/netB.out"

g++ -std=c++11 -O1 NetworkMain.cpp -Wl,--format=binary -Wl,code.zip -Wl,plotFunctions.py -Wl,--format=default -D RECALL_P2 \
    -D CORE_SHAPE_CMD=6 -Wno-unused-result -lboost_serialization -static -o "${out_dir}/netC.out"

rm -f code.zip

cd "${current_working_dir}"
