#!/bin/sh

current_working_dir=${PWD}
cd ..

rm -f code.zip
zip -q -D code.zip * -x *.out *.o *.txt
g++ -std=c++11 \
    -O2 NetworkMain.cpp \
    -Wl,--format=binary -Wl,code.zip -Wl,plotFunctions.py -Wl,--format=default \
    -D INTERMEDIATE_RECALL_P1 \
    -Wno-unused-result \
    -lboost_serialization -static \
    -o "net150_IRS.out"
rm code.zip

cd "${current_working_dir}"
