#!/bin/sh

cd NOOVERLAP/A
cp "../../../../activation/net_activation.out" .
cp "../run" .
cp "../../../1. Priming/NOOVERLAP/A/connections.txt" connections.txt
cp "../../../1. Priming/NOOVERLAP/A/"*/network_plots/*_net_620.0.txt coupling_strengths.txt
cp "../../../../../../analysis/overlapParadigms.py" .
cp "../../../../../../analysis/utilityFunctions.py" .
cp "../../../../../../analysis/assemblyAvalancheStatistics.py" .
screen -d -m /bin/sh run

cd ../..
