#!/bin/sh
rm -f code.zip
zip -q -D code.zip * -x *.out *.o *.txt
g++ -std=c++11 \
    -O2 NetworkMain.cpp \
    -Wl,--format=binary -Wl,code.zip -Wl,plotFunctions.py -Wl,--format=default \
    -D TWO_NEURONS_ONE_SYNAPSE \
    -Wno-unused-result \
    -lboost_serialization -static \
    -o "2N1S.out"
rm code.zip
