#!/bin/sh

cd "OVERLAP10 no BC, no ABC/A"
cp "../../../../activation/net_activation.out" .
cp "../run" .
cp "../../../1. Priming/OVERLAP10 no BC, no ABC/A/connections.txt" connections.txt
cp "../../../1. Priming/OVERLAP10 no BC, no ABC/A/"*/network_plots/*_net_14420.0.txt coupling_strengths.txt
cp "../../../../../../analysis/overlapParadigms.py" .
cp "../../../../../../analysis/utilityFunctions.py" .
cp "../../../../../../analysis/assemblyAvalancheStatistics.py" .
screen -d -m /bin/sh run

cd ../..
