#!/bin/sh
learned_dir="../2nd"

### NO ###
cd NOOVERLAP
cp "../$learned_dir/NOOVERLAP/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run

cd ..
