#!/bin/sh
learned_dir="../2nd"

### 10 ###
cd OVERLAP15
cp "../$learned_dir/OVERLAP15/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run
cd "../OVERLAP15 no ABC"
cp "../$learned_dir/OVERLAP15/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run
cd "../OVERLAP15 no AC, no ABC"
cp "../$learned_dir/OVERLAP15/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run
cd "../OVERLAP15 no BC, no ABC"
cp "../$learned_dir/OVERLAP15/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run

cd ..
