#!/bin/sh
learned_dir="../2nd"

### 10 ###
cd OVERLAP20
cp "../$learned_dir/OVERLAP20/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run
cd "../OVERLAP20 no ABC"
cp "../$learned_dir/OVERLAP20/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run
cd "../OVERLAP20 no AC, no ABC"
cp "../$learned_dir/OVERLAP20/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run
cd "../OVERLAP20 no BC, no ABC"
cp "../$learned_dir/OVERLAP20/"*/*"_connections.txt" connections.txt
cp "../$learned_dir/"*/*/*"_net_28810.0.txt" coupling_strengths.txt
screen -d -m /bin/sh run

cd ..
