#!/bin/sh

current_working_dir=${PWD}
cd ..

out_dir="../simulation-bin/run_binary_misc"
mkdir -p "${out_dir}"

rm -f code.zip
zip -q -D code.zip * -x *.out *.o *.txt
g++ -std=c++11 -O1 NetworkMain.cpp -Wl,--format=binary -Wl,code.zip -Wl,plotFunctions.py -Wl,--format=default -D MEMORY_CONSOLIDATION_P1 \
    -D CORE_SIZE_CMD=200 -Wno-unused-result -lboost_serialization -static -o "${out_dir}/net200.out"
rm -f code.zip

cd "${current_working_dir}"
